In [405]:
import torch
import numpy as np

cigan  = torch.tensor([[[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]],[[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]]])
print(cigan.softmax(dim = 0))
print(cigan.shape)

tensor([[[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000]]])
torch.Size([2, 3, 4])


In [392]:

def Softmax(data , axis = None): 
        
    z = data - np.max(data)
    rom = np.exp(z)
    print(f"rom shape  = {rom.shape}")
    output_T = rom / np.sum(rom, axis = axis)

    return output_T

In [413]:
esk = np.array([[[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]],[[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]]])
out = Softmax(esk, axis = 0)
print(out)

rom shape  = (2, 3, 4)


ValueError: operands could not be broadcast together with shapes (2,3,4) (12,1) 

In [391]:
print(np.sum(esk, axis =1))

[4 4 4]


In [385]:
#from Mini.Tensor import Tensor
#rom = Tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
#
#out = Softmax(rom, axis = 1)
#print(out)
#
#

In [341]:
np.random.seed(100)
T1 = np.random.randn(4,4)
T2 = np.random.randn(4,4)
T3 = np.random.randn(4,4)


In [344]:
true_hat = Tensor([[1], [0], [0], [0]])

torch.manual_seed(100)
t1_ = Tensor(T1)                                         
t2_ = Tensor(T2)                                        
t3_ = Tensor(T3)  * 0.1                                 

first_ = t1_.dot(t2_)                                 
second_ = first_ + t3_                             
third_ =second_.Softmax(axis = 0 )                               
LOSS = -(true_hat * (third_.log())).sum()                                
LOSS.backward()                                               
print(LOSS)
print(third_.shape)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [338]:
print(third_)

<Tensor = [[0.0749  0.01202 0.06371 0.47772]
 [0.03095 0.08097 0.0063  0.01651]
 [0.0172  0.01037 0.01095 0.00366]
 [0.09303 0.04134 0.02075 0.03961]]>


In [302]:
#                               LOG_SOFTMAX                                 #
true_hat_1  = torch.Tensor([[1], [0], [0], [0]])
torch.manual_seed(100)
t1_1 = torch.randn((4,4))                                        ;t1_1.requires_grad = True 
t2_1 = torch.randn((4,1))                                        ;t2_1.requires_grad = True
t3_1 = torch.randn((4,1))  * 0.1                                 ;t3_1.requires_grad = True


first_1 = t1_1.matmul(t2_1)                                        ; first_1.retain_grad()
second_1 = first_1 + t3_1                                          ; second_1.retain_grad()
third_1 =second_1.softmax(dim = 0)                                ; third_1.retain_grad()                     
loss_2 = -torch.sum(true_hat_1 * torch.log(third_1))

loss_2.backward()                                                       ;loss_2.retain_grad()

In [336]:
print(third_1)

tensor(1.0000, grad_fn=<SumBackward0>)


In [300]:
print(loss_2)
print(third_1.grad)

tensor(1.6821, grad_fn=<NegBackward0>)
tensor([[-5.3766],
        [-0.0000],
        [-0.0000],
        [-0.0000]])


In [276]:
der_third = third_1.detach().numpy()
t = third_1.detach().numpy()

softmax_der  = np.dot(np.diagflat(t)  -t.T * t, der_third) 
softmax_der

array([[29.07968],
       [11.90041],
       [20.62231],
       [61.90045]], dtype=float32)

In [271]:
print(third_1.grad)
print(second_1.grad)

tensor([[0.5945],
        [0.0000],
        [0.0000],
        [0.0000]])
tensor([[ 0.4839],
        [-0.2869],
        [-0.1746],
        [-0.0224]])


In [ ]:

loss_fn = torch.nn.CrossEntropyLoss()
true_hat = torch.tensor([1.,0.,0.,0.])
#true_hat = torch.Tensor([1,0,0,0])

torch.manual_seed(100)
t1_ = torch.randn((4,4))                                        ;t1_.requires_grad = True 
t2_ = torch.randn((4,1))                                        ;t2_.requires_grad = True
t3_ = torch.randn((4,1))  * 0.1                                 ;t3_.requires_grad = True


first_ = t1_.matmul(t2_)                                        ; first_.retain_grad()
second_ = first_ + t3_                                          ; second_.retain_grad()
third_ =second_.softmax(dim = 0)                               ; third_.retain_grad()  
loss = loss_fn(second_.squeeze(), true_hat)                                 ; loss.retain_grad()
loss.backward()                                               
print(LOSS)