In [1]:
from Mini.Tensor import Tensor
import torch
import numpy as np

c:\Users\pavle\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
np.random.seed(100)
T1 = np.random.randn(4,4)
T2 = np.random.randn(4,1)
T3 = np.random.randn(4,1)


In [3]:
true_hat = Tensor([[1], [0], [0], [0]])

torch.manual_seed(100)
t1_ = Tensor(T1)                                         
t2_ = Tensor(T2)                                        
t3_ = Tensor(T3)  * 0.1                                 

first_ = t1_.dot(t2_)                                 
second_ = first_ + t3_                             
third_ =second_.Softmax(axis = 0)                               
LOSS = -(true_hat * (third_.log())).sum() 
LOSS.backward()                               
print(LOSS)


<Tensor = 1.1213652686490223>


In [4]:
print(third_.grad)
print(second_.grad)


<Tensor = [[-3.06904]
 [ 0.     ]
 [ 0.     ]
 [ 0.     ]]>
<Tensor = [[-0.67417]
 [ 0.33932]
 [ 0.10119]
 [ 0.23366]]>


In [5]:
print(t1_.grad)

<Tensor = [[ 0.35817 -0.69421  0.29538  0.75393]
 [-0.18027  0.34941 -0.14867 -0.37947]
 [-0.05376  0.1042  -0.04433 -0.11316]
 [-0.12414  0.2406  -0.10237 -0.2613 ]]>


In [6]:
print(third_)

<Tensor = [[0.32583]
 [0.33932]
 [0.10119]
 [0.23366]]>


In [7]:
#                               LOG_SOFTMAX                                 #
true_hat_1  = torch.Tensor([[1], [0], [0], [0]])
torch.manual_seed(100)
t1_1 = torch.tensor(T1)                                        ;t1_1.requires_grad = True 
t2_1 = torch.tensor(T2)                                        ;t2_1.requires_grad = True
t3_1 = torch.tensor(T3)  * 0.1                                 ;t3_1.requires_grad = True


first_1 = t1_1.matmul(t2_1)                                        ; first_1.retain_grad()
second_1 = first_1 + t3_1                                          ; second_1.retain_grad()
third_1 =second_1.softmax(dim = 0)                                ; third_1.retain_grad()                     
loss_2 = -torch.sum(true_hat_1 * torch.log(third_1))

loss_2.backward()                                                       ;loss_2.retain_grad()

In [8]:
print(third_1.grad)
print(second_1.grad)

tensor([[-3.0690],
        [-0.0000],
        [-0.0000],
        [-0.0000]], dtype=torch.float64)
tensor([[-0.6742],
        [ 0.3393],
        [ 0.1012],
        [ 0.2337]], dtype=torch.float64)


In [9]:
second_grad  =  Tensor(np.matmul((np.diagflat(third_.data) - np.dot(third_.data, third_.data.T)), third_.grad.data))
print(second_grad)

<Tensor = [[-0.67417]
 [ 0.33932]
 [ 0.10119]
 [ 0.23366]]>
